pipeline {
    agent any
 
    tools {
        maven 'Maven3'
        jdk  'JDK'
    }
 
    stages {
 
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/vaishali1912/SDET_wipro_2026'
            }
        }
 
        stage('Build') {
            steps {
                dir('Maven_Test_code') {
                    bat 'mvn clean'
                }
            }
        }
 
        stage('Compile') {
            steps {
                dir('Maven_Test_code') {
                    bat 'mvn compile'
                }
            }
        }
 
        stage('Test') {
            steps {
                dir('Maven_Test_code') {
                    bat 'mvn test'
                }
            }
        }
 
        stage('Package') {
            steps {
                dir('Maven_Test_code') {
                    bat 'mvn package'
                }
            }
        }
    }
 
    post {
        success {
            echo 'Build Successful'
        }
 
        failure {
            echo 'Build Failed'
        }
    }
}
 
